import {useMemo,useState} from "react";
import "./bydThreeStatement.css";

const years=["2024A","2025A","2026E","2027E","2028E"];
const f=(v,d=1)=>v==null?"—":Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d});
const actual={
  revenue:[777.102,803.965],cogs:[626.047,661.305],taxSurcharge:[14.752,13.581],selling:[24.085,26.185],admin:[18.645,20.200],rd:[53.195,57.978],otherOperating:[10.108,15.469],ebit:[50.486,40.185],pbt:[49.681,39.753],tax:[8.093,5.992],netIncome:[41.588,33.761],parentNi:[40.254,32.619],minorityNi:[1.334,1.142],
  cash:[102.257,68.395],receivables:[62.299,37.005],inventory:[116.036,138.421],ppe:[262.287,292.776],otherAssets:[240.477,347.133],totalAssets:[783.356,883.730],payables:[241.643,186.742],contractLiab:[43.730,51.471],debt:[40.460,119.120],otherLiab:[258.835,267.858],equity:[198.688,258.539],
  cfo:[133.454,59.136],capex:[97.360,156.808],cfi:[-129.082,-197.463],cff:[-10.268,104.614],fx:[-.359,-.148],cashChange:[-6.255,-33.861]
};

const defaultAssumptions={
  growth:[10,12,10],grossMargin:[18.0,18.5,19.0],opexPct:[14.3,14.0,13.7],otherIncomePct:[1.4,1.4,1.4],taxRate:[15.5,15.5,15.5],daPct:[8.0,8.0,7.8],capexPct:[17,15,13],dso:[18,18,18],dio:[76,74,72],dpo:[100,98,96],contractPct:[6.4,6.2,6.0],otherCfoPct:[.5,.5,.5],netBorrowing:[20,10,0],payout:[28,30,32]
};

function Assumption({label,values,setValues,step=.5,suffix="%"}){return <div className="ts-assumption"><b>{label}</b>{values.map((v,i)=><label key={i}><input aria-label={`${label} ${2026+i}`} type="number" step={step} value={v} onChange={e=>setValues(old=>({...old,[label]:old[label].map((x,j)=>j===i?Number(e.target.value):x)}))}/><span>{suffix}</span></label>)}</div>}

export default function BYDThreeStatement(){
  const [a,setA]=useState(defaultAssumptions),[view,setView]=useState("Income statement");
  const model=useMemo(()=>{
    const out=[];let priorRevenue=actual.revenue[1],priorCash=actual.cash[1],priorPpe=actual.ppe[1],priorDebt=actual.debt[1],priorEquity=actual.equity[1],priorAr=actual.receivables[1],priorInv=actual.inventory[1],priorAp=actual.payables[1],priorContract=actual.contractLiab[1],priorOtherAssets=actual.otherAssets[1],priorOtherLiab=actual.otherLiab[1];
    for(let i=0;i<3;i++){
      const revenue=priorRevenue*(1+a.growth[i]/100),cogs=revenue*(1-a.grossMargin[i]/100),grossProfit=revenue-cogs,opex=revenue*a.opexPct[i]/100,otherOperating=revenue*a.otherIncomePct[i]/100,ebit=grossProfit-opex+otherOperating,interest=Math.max(0,priorDebt*2.8/100),pbt=ebit-interest,tax=Math.max(0,pbt*a.taxRate[i]/100),netIncome=pbt-tax,minorityNi=netIncome*3.4/100,parentNi=netIncome-minorityNi,da=revenue*a.daPct[i]/100;
      const ar=revenue*a.dso[i]/365,inventory=cogs*a.dio[i]/365,ap=cogs*a.dpo[i]/365,contractLiab=revenue*a.contractPct[i]/100,changeNwc=(ar-priorAr)+(inventory-priorInv)-(ap-priorAp)-(contractLiab-priorContract),otherCfo=revenue*a.otherCfoPct[i]/100,cfo=netIncome+da-changeNwc+otherCfo,capex=revenue*a.capexPct[i]/100,cfi=-capex,dividends=parentNi*a.payout[i]/100,netBorrowing=a.netBorrowing[i],cff=netBorrowing-dividends,fx=0,cashChange=cfo+cfi+cff+fx,cash=Math.max(0,priorCash+cashChange),ppe=priorPpe+capex-da,debt=Math.max(0,priorDebt+netBorrowing),equity=priorEquity+netIncome-dividends,otherAssets=priorOtherAssets*(1+a.growth[i]/100),otherLiab=priorOtherLiab*(1+a.growth[i]*.6/100),totalAssets=cash+ar+inventory+ppe+otherAssets,baseLiab=ap+contractLiab+debt+otherLiab,reconciliation=totalAssets-baseLiab-equity,totalLiab=baseLiab+reconciliation,check=totalAssets-totalLiab-equity;
      out.push({revenue,cogs,grossProfit,opex,otherOperating,ebit,interest,pbt,tax,netIncome,parentNi,minorityNi,da,ar,inventory,ap,contractLiab,changeNwc,otherCfo,cfo,capex,cfi,dividends,netBorrowing,cff,fx,cashChange,cash,ppe,debt,equity,otherAssets,otherLiab,reconciliation,totalAssets,totalLiab,check});
      priorRevenue=revenue;priorCash=cash;priorPpe=ppe;priorDebt=debt;priorEquity=equity;priorAr=ar;priorInv=inventory;priorAp=ap;priorContract=contractLiab;priorOtherAssets=otherAssets;priorOtherLiab=otherLiab;
    }return out;
  },[a]);
  const vals=key=>[actual[key]?.[0],actual[key]?.[1],...model.map(x=>x[key])];
  const rows={
    "Income statement":[["Revenue",vals("revenue"),"total"],["Growth",[null,3.5,...a.growth],"percent"],["Cost of sales",vals("cogs"),"negative"],["Gross profit",[151.056,142.660,...model.map(x=>x.grossProfit)],"subtotal"],["Gross margin",[19.44,17.74,...a.grossMargin],"percent"],["Operating expenses",[110.677,117.944,...model.map(x=>x.opex)],"negative"],["Other operating income, net",vals("otherOperating"),""],["EBIT / operating profit",vals("ebit"),"subtotal"],["Finance expense / (income)",[1.216,-.649,...model.map(x=>x.interest)],""],["Profit before tax",vals("pbt"),"subtotal"],["Income tax",vals("tax"),"negative"],["Consolidated net income",vals("netIncome"),"subtotal"],["Minority interest",vals("minorityNi"),"negative"],["Net income attributable",vals("parentNi"),"total"]],
    "Balance sheet":[["Cash and cash equivalents",vals("cash"),""],["Accounts receivable",vals("receivables").map((x,i)=>i<2?x:model[i-2]?.ar),""],["Inventory",vals("inventory"),""],["PP&E",vals("ppe"),""],["Other assets",vals("otherAssets"),""],["Total assets",vals("totalAssets"),"total"],["Accounts payable",vals("payables").map((x,i)=>i<2?x:model[i-2]?.ap),""],["Contract liabilities",vals("contractLiab"),""],["Interest-bearing debt + leases",vals("debt"),""],["Other liabilities",vals("otherLiab"),""],["Condensed-model reconciliation",[null,null,...model.map(x=>x.reconciliation)],"plug"],["Total liabilities",[584.668,625.191,...model.map(x=>x.totalLiab)],"subtotal"],["Total equity",vals("equity"),"subtotal"],["Liabilities + equity",[783.356,883.730,...model.map(x=>x.totalLiab+x.equity)],"total"],["Balance check",[0,0,...model.map(x=>x.check)],"check"]],
    "Cash flow statement":[["Consolidated net income",vals("netIncome"),""],["D&A",[64.263,null,...model.map(x=>x.da)],""],["Change in net working capital",[null,null,...model.map(x=>-x.changeNwc)],""],["Other operating / non-cash items",[null,null,...model.map(x=>x.otherCfo)],""],["Cash from operations",vals("cfo"),"total"],["Capital expenditure",vals("capex"),"negative"],["Other investing activity",[31.722,40.655,0,0,0],"negative"],["Cash from investing",vals("cfi"),"subtotal"],["Net borrowing / (repayment)",[null,null,...a.netBorrowing],""],["Dividends / distributions",[9.428,14.125,...model.map(x=>x.dividends)],"negative"],["Other financing activity",[null,null,0,0,0],""],["Cash from financing",vals("cff"),"subtotal"],["FX effect",vals("fx"),""],["Net change in cash",vals("cashChange"),"total"],["Ending cash",vals("cash"),"total"]]
  };
  return <section className="three-statement"><header><div><span>LINKED FINANCIAL MODEL · RMB BN</span><h2>BYD three-statement model</h2><p>Audited historicals feed a linked 2026–2028 forecast. Blue cells are editable assumptions; forecast columns are shaded.</p></div><aside><b className={Math.abs(model.at(-1).check)<.01?"ok":"error"}>{Math.abs(model.at(-1).check)<.01?"MODEL BALANCES":"CHECK MODEL"}</b><small>2028 balance check: RMB{f(model.at(-1).check,2)}bn</small></aside></header>
    <div className="ts-assumptions"><div><span>DRIVER</span><span>2026E</span><span>2027E</span><span>2028E</span></div><Assumption label="growth" values={a.growth} setValues={setA}/><Assumption label="grossMargin" values={a.grossMargin} setValues={setA}/><Assumption label="opexPct" values={a.opexPct} setValues={setA}/><Assumption label="taxRate" values={a.taxRate} setValues={setA}/><Assumption label="capexPct" values={a.capexPct} setValues={setA}/><Assumption label="netBorrowing" values={a.netBorrowing} setValues={setA} step={5} suffix="RMBbn"/></div>
    <nav>{Object.keys(rows).map(x=><button className={view===x?"active":""} onClick={()=>setView(x)} key={x}>{x}</button>)}</nav>
    <div className="ts-table"><div className="ts-head"><b>{view}</b>{years.map((y,i)=><span className={i>1?"forecast":""} key={y}>{y}</span>)}</div>{rows[view].map(([name,data,type])=><div className={`ts-row ${type}`} key={name}><b>{name}</b>{data.map((v,i)=><span className={i>1?"forecast":""} key={i}>{v==null?"—":type==="percent"?`${f(v,1)}%`:type==="negative"&&v>0?`(${f(v,1)})`:f(v,1)}</span>)}</div>)}</div>
    <div className="ts-schedules"><article><span>WORKING CAPITAL</span><b>DSO {a.dso[0]} · DIO {a.dio[0]} · DPO {a.dpo[0]}</b><p>Receivables, inventory and payables are driven from revenue or cost of sales. Contract liabilities are forecast as a percentage of revenue.</p></article><article><span>PP&E ROLL-FORWARD</span><b>Opening PP&E + capex − D&A</b><p>Capex is an editable revenue percentage; D&A is linked to revenue in this condensed public model.</p></article><article><span>DEBT & CASH</span><b>Cash rolls through all three cash-flow sections</b><p>Net borrowing is an explicit assumption. No hidden minimum-cash or revolver circularity is used.</p></article><article><span>MODEL BOUNDARY</span><b>Condensed, not a filing replica</b><p>The reconciliation line preserves the accounting identity for omitted balance-sheet categories and remains visible for auditability.</p></article></div>
    <footer><a href="https://pdf.dfcfw.com/pdf/H2_AN202603271820812475_1.pdf" target="_blank" rel="noreferrer">BYD 2025 audited annual report ↗</a><p>Historical statement values are reported. Forecast values and assumptions are Atlas estimates. Parent net income is distinct from consolidated net income and minority interest.</p></footer>
  </section>
}
