import "./investmentSystem.css";

export const investmentCases={
  australia:{title:"Australia · China-sensitive resource earnings",signal:"MONITOR",tone:"mixed",confidence:"Medium",horizon:"6–24 months",changed:"Export volumes remain structurally competitive, while Chinese steel demand, iron-ore price, producer FX and capital returns drive the equity read-through.",variable:"Pilbara shipments, realized iron-ore price and unit cost",chain:[["SIGNAL","China steel + ore balance","Chinese hot-metal output and inventories set the marginal demand signal.","observed"],["PHYSICAL TRANSMISSION","Mine → rail → port → China","Reliability and freight determine delivered tonnes and quality realization.","observed"],["ESTIMATE IMPACT","Volume × price − unit cost","Revenue and cash flow move through realized pricing, production and cost discipline.","estimated"],["VALUATION","Normalized cash flow + returns","Cycle assumptions and capital allocation matter more than spot-price extrapolation.","estimated"],["DECISION","Monitor cycle and execution","Separate durable cost advantage from commodity-price direction.","hypothesis"]],winners:"Low-cost, reliable Australian producers",losers:"High-cost supply if Chinese demand weakens",breakRule:"Sustained Chinese hot-metal contraction combines with volume or cost misses"},
  indonesia:{title:"Indonesia · nickel downstreaming versus oversupply",signal:"MONITOR",tone:"mixed",confidence:"Medium",horizon:"1–3 years",changed:"Policy-backed processing investment increases Indonesia’s industrial share, while rapid supply growth pressures nickel prices and project returns.",variable:"Nickel output, realized price, processing utilization and project returns",chain:[["SIGNAL","Quota + policy + investment","Ore policy and permitting govern the pace and location of supply.","observed"],["PHYSICAL TRANSMISSION","Ore → NPI/matte/MHP","Processing route determines end market, cost and battery relevance.","observed"],["ESTIMATE IMPACT","Volume ↑ · price/margin ↓","Producer earnings depend on cost position and contracts as aggregate supply grows.","estimated"],["VALUATION","Through-cycle margin + country risk","Growth deserves value only where returns survive lower prices.","estimated"],["DECISION","Prefer advantaged assets","Do not equate national production growth with shareholder value.","hypothesis"]],winners:"Low-cost integrated processors with secured ore and power",losers:"High-cost nickel projects and undifferentiated capacity",breakRule:"Quota restraint or curtailments tighten the balance faster than expected"},
  byd:{
    title:"BYD · overseas growth versus earnings quality",signal:"WATCH",tone:"mixed",confidence:"Medium",horizon:"6–18 months",
    changed:"Overseas volume is scaling while Chinese price competition, working-capital normalization and localization capex pressure cash conversion.",
    variable:"Overseas mix, auto gross margin and operating cash conversion",
    chain:[
      ["SIGNAL","China demand + nickel/lithium balance","Domestic pricing remains competitive; battery inputs offer a partial cost offset.","observed"],
      ["PHYSICAL TRANSMISSION","Battery → EV → overseas plants","Vertical integration and localization determine how much of the input benefit reaches vehicle economics.","estimated"],
      ["ESTIMATE IMPACT","Units ↑ · margin uncertain · capex elevated","FY2027E earnings rise only if profitable overseas mix offsets domestic margin and cash-conversion pressure.","estimated"],
      ["VALUATION","DCF + forward P/E","The target must be supported by cash generation as well as unit growth; implied P/E is the sanity check.","estimated"],
      ["DECISION","Wait for confirmation","Become constructive after sustained margin and operating-cash-flow improvement; downgrade on leverage without returns.","hypothesis"]
    ],
    winners:"BYD if localized overseas production converts volume into margin and cash",losers:"Undifferentiated domestic EV capacity and high-cost battery suppliers",breakRule:"Two reporting periods of weaker group margin and cash conversion while leverage rises"
  },
  clf:{title:"Cleveland-Cliffs · protected pricing versus fixed-cost leverage",signal:"WATCH",tone:"mixed",confidence:"Medium",horizon:"3–12 months",changed:"US trade protection supports regional steel pricing, but automotive demand and utilization determine whether price reaches EBITDA and free cash flow.",variable:"Realized revenue/ton, shipments and EBITDA/ton",chain:[["SIGNAL","Tariffs + US industrial demand","Import parity can support price while auto and manufacturing volumes set physical demand.","observed"],["PHYSICAL TRANSMISSION","Domestic steel system","Product mix, contracts and utilization determine realized pricing and fixed-cost absorption.","estimated"],["ESTIMATE IMPACT","EBITDA/ton + FCF","A price move matters only if shipment and cost performance preserve the spread.","estimated"],["VALUATION","Cycle EV/EBITDA less net debt","Equity value is highly sensitive to normalized EBITDA and deleveraging.","estimated"],["DECISION","Require cash confirmation","Upgrade on shipment recovery and positive FCF; break on weak auto demand and persistent leverage.","hypothesis"]],winners:"Efficient domestic mills with contract repricing",losers:"Steel-consuming manufacturers if protection raises input costs",breakRule:"Higher HRC prices fail to improve EBITDA/ton or free cash flow"},
  equinix:{title:"Equinix · AI demand versus capital intensity",signal:"WATCH",tone:"mixed",confidence:"Medium",horizon:"6–24 months",changed:"AI and cloud demand support bookings, while power availability, development returns and rates govern value creation.",variable:"Bookings conversion, AFFO/share and return on incremental capital",chain:[["SIGNAL","AI capex + power constraints","Demand is strong, but usable powered capacity—not announcements—sets deliverable growth.","observed"],["PHYSICAL TRANSMISSION","Data-center construction","Grid access, equipment, steel and construction schedules control time-to-revenue.","estimated"],["ESTIMATE IMPACT","Revenue + AFFO/share","Bookings must convert faster than development capital and financing costs grow.","estimated"],["VALUATION","P/AFFO + rate sensitivity","A premium multiple requires durable per-share growth and acceptable incremental returns.","estimated"],["DECISION","Monitor conversion","Upgrade on AFFO revisions and stable returns; break on capex growth without per-share value.","hypothesis"]],winners:"Scaled operators with secured power and interconnection ecosystems",losers:"Unpowered speculative capacity and low-return development",breakRule:"Capital expenditure rises without corresponding AFFO/share revisions"},
  mongolia:{title:"Mongolia–China rail · execution, not announced capacity",signal:"MONITOR",tone:"mixed",confidence:"Medium",horizon:"12–36 months",changed:"A planned 40 Mtpa connection and contracted transport volume create credible supply potential, but construction and border throughput determine realized tonnes.",variable:"Landborne coking-coal volume and delivered cost",chain:[["SIGNAL","Rail milestones + border throughput","Physical completion and customs capacity determine the ramp.","observed"],["PHYSICAL TRANSMISSION","Mongolia → Chinese mills","More reliable rail supply can displace higher-cost trucked or seaborne tonnes.","estimated"],["ESTIMATE IMPACT","Coal price + mill input cost","Realized volume could pressure regional coal prices and modestly improve BF mill spreads.","estimated"],["VALUATION","Miner volume/price sensitivities","Beneficiary and loser estimates depend on contract pricing and displacement, not headline capacity.","estimated"],["DECISION","Track milestones","Do not underwrite national aspirations before construction and throughput evidence.","hypothesis"]],winners:"Low-cost Mongolian producers and connected Chinese mills",losers:"Marginal seaborne or trucked supply if displacement is realized",breakRule:"Construction slips or border throughput fails to scale after commissioning"},
  eaf:{title:"China EAF transition · utilization before capacity",signal:"MONITOR",tone:"mixed",confidence:"Medium-high",horizon:"2–5 years",changed:"Policy and recycling initiatives support EAF investment, but scrap quality, power economics and product qualification constrain utilization.",variable:"EAF utilization, scrap spread and product mix",chain:[["SIGNAL","Policy + recycling volumes","Collection reform can improve scrap availability and consistency.","observed"],["PHYSICAL TRANSMISSION","Scrap/power → EAF steel","Delivered scrap quality and regional electricity determine operating economics.","estimated"],["ESTIMATE IMPACT","Metallic mix + mill margin","Higher utilization reduces ore intensity; flat/auto penetration requires qualification.","estimated"],["VALUATION","Cost position + transition capex","Value accrues only where utilization and product capability earn returns.","estimated"],["DECISION","Track realized economics","Installed capacity alone is not evidence of competitiveness.","hypothesis"]],winners:"Efficient EAF mills, recyclers and qualified scrap processors",losers:"Marginal ore-based capacity if EAF economics become durable",breakRule:"Scrap and power spreads keep EAF utilization structurally low"}
};

export function InvestmentTransmission({caseData,compact=false}){
  if(!caseData)return null;
  return <section className={`investment-transmission ${compact?"compact":""}`}>
    <header><div><span>INVESTMENT TRANSMISSION</span><h2>{caseData.title}</h2><p>{caseData.changed}</p></div><aside className={caseData.tone}><small>SIGNAL</small><b>{caseData.signal}</b><em>{caseData.confidence} confidence · {caseData.horizon}</em></aside></header>
    <div className="transmission-variable"><span>VARIABLE THAT MUST MOVE</span><b>{caseData.variable}</b></div>
    <div className="transmission-chain">{caseData.chain.map(([stage,title,detail,status],i)=><article key={stage}><span>{String(i+1).padStart(2,"0")} · {stage}</span><b>{title}</b><p>{detail}</p><em className={status}>{status}</em></article>)}</div>
    <footer><div><span>PRIMARY BENEFICIARY</span><b>{caseData.winners}</b></div><div><span>PRIMARY LOSER / RISK</span><b>{caseData.losers}</b></div><div><span>DISCONFIRMATION RULE</span><b>{caseData.breakRule}</b></div></footer>
  </section>
}

export function IdeaMonitor({onNavigate}){
  const rows=[investmentCases.byd,investmentCases.clf,investmentCases.equinix,investmentCases.mongolia,investmentCases.eaf];
  return <section className="idea-monitor"><header><div><span>INVESTMENT DECISION MONITOR</span><h2>Where the Atlas currently has a view</h2></div><p>Signals are research conclusions, not simulated positions. Each row links an external change to a measurable estimate and a rule for changing the view.</p></header><div className="idea-table"><div><span>Idea</span><span>Signal</span><span>Key variable</span><span>Horizon</span><span>Next evidence</span></div>{rows.map((x,i)=><button key={x.title} onClick={()=>onNavigate?.(i<3?"companies":"research",x.title)}><b>{x.title.split(" · ")[0]}</b><strong className={x.tone}>{x.signal}</strong><span>{x.variable}</span><span>{x.horizon}</span><small>{x.breakRule}</small></button>)}</div></section>
}
