import {useMemo,useState} from "react";
import "./pmInvestment.css";
import "./institutional.css";
import {ResearchNote} from "./ResearchNote.jsx";
import {companyNarratives} from "./companyNarratives.js";
import {InvestmentTransmission,investmentCases} from "./InvestmentSystem.jsx";

const DISCLOSURE="Analytical research prototype, not personalized investment advice. Public sources only.";

const money=(v,d=1)=>Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d});
const pct=v=>`${v>=0?"+":""}${money(v,1)}%`;
const navigateAtlas=(tab,context)=>{window.__atlasDestination={tab,context};window.dispatchEvent(new CustomEvent("atlas:navigate",{detail:{tab,context}}))};

export function InstitutionalBrief({debate,variant,estimate,catalyst,risk}){
  return <section className="institutional-brief"><article><span>CORE DEBATE</span><b>{debate}</b></article><article><span>VARIANT VIEW</span><b>{variant}</b></article><article><span>ESTIMATE DIRECTION</span><b>{estimate}</b></article><article><span>CATALYST</span><b>{catalyst}</b></article><article><span>DOWNSIDE / DISCONFIRMATION</span><b>{risk}</b></article></section>
}
function CommercialResearch({deep}){return <><h2 className="section-title">Commercial disclosures and unresolved diligence</h2><div className="commercial-diligence"><article><span>CONTRACTS</span><b>PARTIALLY DISCLOSED</b><p>{deep.contracts}</p></article><article><span>HEDGES / PASS-THROUGH</span><b>RESEARCH IN PROGRESS</b><p>{deep.hedges}</p></article><article><span>CONSENSUS</span><b>NOT SILENTLY IMPUTED</b><p>No live institutional consensus feed is connected. Company guidance, reported figures and Atlas assumptions remain separate.</p></article></div></>}

export function InvestmentCompanyPage({company,profile,deep,quote,onBack}){
  if(company.id==="cleveland-cliffs")return <CliffsWorkbench {...{company,profile,deep,quote,onBack}}/>;
  if(company.id==="equinix")return <><EquinixWorkbench {...{company,profile,deep,quote,onBack}}/><EquinixRevision/></>;
  return <StandardSectorWorkbench {...{company,profile,deep,quote,onBack}}/>;
}

const sectorModels={
  rio:{label:"Commodity and capital-allocation model",signal:"Commodity cash-flow",inputs:[
    ["Normalized EBITDA",25.4,15,38,.5,"US$bn","2025 underlying EBITDA: US$25.363bn"],
    ["Target EV / EBITDA",7,4,11,.25,"×","Through-cycle analyst assumption"],
    ["Net debt",14.4,5,25,.5,"US$bn","2025 net debt: US$14.362bn"],
    ["Sustaining + growth capex",11,6,16,.5,"US$bn","Separates cash conversion from headline EBITDA"]],
    output:v=>({primary:v[0]*v[1]-v[2],label:"Implied equity value",unit:"US$bn",secondary:[["Enterprise value",v[0]*v[1],"US$bn"],["FCF proxy",v[0]-v[3],"US$bn"],["Net debt / EBITDA",v[2]/v[0],"×"]]}),
    expectations:[["Pilbara shipments","Operational guidance / company reporting","Atlas monitoring"],["Iron-ore benchmark","Market input—not company guidance","Scenario driver"],["Copper growth","Project delivery milestones","Upside optionality"],["Capital returns","Board decision after capex and leverage","Not assumed"]],
    breaks:[["Pilbara reliability","Two material volume misses","Reduce"],["Net debt / EBITDA",">1.0× without growth delivery","Review"],["Growth capex",">15% over plan","Cut value"],["China steel","Sustained contraction","Lower normalized EBITDA"]],
    links:[["Iron ore","Price, quality and Pilbara volumes"],["Copper","Growth-project delivery and mix"],["China","Steel production and import demand"],["Shipping","Freight and route reliability"]]
  },
  arcelormittal:{label:"Steel spread and utilization model",signal:"Steel-cycle",inputs:[
    ["Steel shipments",56,48,64,1,"Mt","2025 shipments: 54.0Mt"],["EBITDA / tonne",140,70,240,5,"US$/t","2025 reported proxy: approximately US$121/t"],["Target EV / EBITDA",6,3.5,9,.25,"×","Regional diversification and cycle assumption"],["Net debt adjustment",8,0,18,.5,"US$bn","Editable pending latest definition reconciliation"]],
    output:v=>{const e=v[0]*v[1]/1000;return {primary:e*v[2]-v[3],label:"Implied equity value",unit:"US$bn",secondary:[["Normalized EBITDA",e,"US$bn"],["Enterprise value",e*v[2],"US$bn"],["EBITDA / tonne",v[1],"US$/t"]]}},
    expectations:[["Steel shipments","2025 actual: 54.0Mt","56Mt Atlas base"],["EBITDA / tonne","2025 proxy: ~$121/t","Editable normalized margin"],["Utilization","Regional operating evidence","Key confirmation"],["Trade policy","Safeguards and tariffs","Regional spread catalyst"]],
    breaks:[["EBITDA / tonne","Below $100/t through recovery","Reduce"],["Shipments","Below 52Mt run-rate","Review"],["Growth projects","Ramp misses two milestones","Cut value"],["Net debt","Rises through positive cycle","No add"]],
    links:[["Steel","Regional prices, capacity and utilization"],["Iron ore","Mining integration and input costs"],["Energy","European power and carbon exposure"],["Trade policy","Import pressure and safeguards"]]
  },
  catl:{label:"Battery volume and margin model",signal:"Battery demand",inputs:[
    ["Battery shipments",720,550,900,10,"GWh","2025 battery sales: 661GWh"],["Net profit / GWh",.105,.055,.15,.005,"RMBbn/GWh","Captures price, mix, utilization and non-cell earnings"],["Target P / E",24,14,36,1,"×","Growth and technology-premium assumption"],["Diluted shares",4.55,4.2,4.9,.05,"bn","Placeholder pending fully diluted reconciliation"]],
    output:v=>{const p=v[0]*v[1],eq=p*v[2];return {primary:eq/v[3],label:"Implied value / share",unit:"RMB",secondary:[["Normalized net profit",p,"RMBbn"],["Implied equity value",eq,"RMBbn"],["Shipment growth vs 2025",100*(v[0]/661-1),"%"]]}},
    expectations:[["Battery shipments","2025 actual: 661GWh","Editable 2026 scenario"],["Pricing and mix","No silent consensus","Profit/GWh captures outcome"],["Overseas ramp","Plant and customer milestones","Return-on-capital test"],["Energy storage","Atlas demand evidence","Potential mix support"]],
    breaks:[["Shipments","Growth below 10%","Review"],["Profit / GWh","Below RMB0.08bn","Reduce"],["Overseas utilization","Two ramp delays","Cut multiple"],["Technology share","Material chemistry displacement","Rebuild thesis"]],
    links:[["Batteries","Cell capacity, chemistry and utilization"],["Lithium / nickel","Raw-material prices and pass-through"],["EV","Regional production and sales"],["Policy","Localization rules and overseas capex"]]
  },
  "hd-hyundai-shipbuilding":{label:"Backlog conversion and margin model",signal:"Shipyard earnings",inputs:[
    ["Shipbuilding revenue",32,26,38,.5,"KRWtn","2025 shipbuilding revenue: KRW29.933tn"],["Operating margin",13,7,18,.5,"%","2025 derived margin: approximately 13%"],["Target EV / EBIT",9,5,14,.5,"×","Backlog quality and execution assumption"],["Net debt adjustment",3,0,8,.25,"KRWtn","Illustrative pending listed-entity boundary reconciliation"]],
    output:v=>{const op=v[0]*v[1]/100;return {primary:op*v[2]-v[3],label:"Implied equity value",unit:"KRWtn",secondary:[["Operating profit",op,"KRWtn"],["Enterprise value",op*v[2],"KRWtn"],["Operating margin",v[1],"%"]]}},
    expectations:[["Revenue conversion","Backlog delivery schedule","Primary forecast anchor"],["Operating margin","2025 derived: ~13%","Mix and productivity test"],["Steel plate costs","Atlas steel-price evidence","Contract-margin sensitivity"],["Order quality","LNG and high-value vessel mix","Future margin indicator"]],
    breaks:[["Operating margin","Below 10% after mix improves","Reduce"],["Deliveries","Repeated schedule slippage","Review"],["Labor productivity","Cost growth exceeds pricing","Cut value"],["Orderbook","Low-value orders dilute mix","Lower multiple"]],
    links:[["Shipbuilding","Orders, completions and yard capacity"],["Steel","Plate availability and input cost"],["LNG shipping","High-value vessel demand"],["Trade routes","Fleet demand and chokepoint effects"]]
  }
};

function StandardSectorWorkbench({company,profile,deep,quote,onBack}){
  const model=sectorModels[company.id],initial=model.inputs.map(x=>x[1]),[values,setValues]=useState(initial),result=model.output(values),price=quote?.live?quote.price:null;
  const unresolvedInputs=model.inputs.filter(x=>/placeholder|pending|reconciliation/i.test(x[6]));
  const update=(i,v)=>setValues(old=>old.map((x,j)=>j===i?v:x));
  const narrative=companyNarratives[company.id];
  const keyData=[["Ticker",profile.ticker],["Sector",profile.sector],["Share price",quote?.live?`${quote.price.toFixed(2)} ${quote.currency}`:"Feed unavailable"],["Atlas stance",deep.stance],["Conviction",deep.conviction],[result.label,`${result.unit} ${money(result.primary,2)}`],["As of",deep.asOf]];
  return <section className="directory-page pm-company"><button className="finance-back" onClick={onBack}>← Companies by industry</button>
    <ResearchNote eyebrow={`${profile.sector} · FUNDAMENTAL WORKBENCH`} companyName={company.name} strapline={narrative?.strapline} narrative={narrative} keyData={keyData} quote={quote} symbol={profile.marketSymbol} disclosure={DISCLOSURE}/>
    <DecisionCard side={deep.stance} price={price} target={null} bear={null} horizon="6–18 months" confidence={deep.conviction} status="MODEL ACTIVE" catalyst={profile.catalysts[0]} breakRule={model.breaks[0][1]}/>
    <InstitutionalBrief debate={profile.debate} variant={deep.variant} estimate="Company anchors remain separate from Atlas assumptions; revise only when operating evidence changes." catalyst={profile.catalysts[0]} risk={profile.risks[0]}/>
    {investmentCases[company.id]&&<InvestmentTransmission caseData={investmentCases[company.id]}/>} 
    {unresolvedInputs.length>0&&<section className="model-readiness-warning"><span>MODEL INTEGRITY · NOT YET DECISION-READY</span><b>{unresolvedInputs.length} material input{unresolvedInputs.length===1?"":"s"} require reconciliation</b><p>{unresolvedInputs.map(x=>x[0]).join(" · ")}. Scenario outputs remain useful for sensitivity analysis, but should not be presented as a target price until these inputs are sourced.</p></section>}
    <div className="pm-three-sentence"><span>INVESTMENT CONCLUSION</span><p>{deep.recommendation}</p></div>
    <h2 className="section-title">Financial and operating snapshot</h2><div className="finance-metrics sector-metrics">{deep.metrics.map(([name,value,unit,change])=><article key={name}><span>{deep.asOf}</span><b>{Number(value).toLocaleString(undefined,{maximumFractionDigits:3})} {unit}</b><h3>{name}</h3><strong className={String(change).startsWith("−")?"negative":"positive"}>{change}</strong></article>)}</div>
    <h2 className="section-title">{model.label}</h2><div className="pm-model"><div className="pm-inputs">{model.inputs.map((x,i)=><Range key={x[0]} label={x[0]} value={values[i]} set={v=>update(i,v)} min={x[2]} max={x[3]} step={x[4]} unit={x[5]} reported={x[6]}/>)}</div><div className="pm-output"><span>ATLAS BASE OUTPUT</span><b>{result.unit} {money(result.primary,2)}</b><dl>{result.secondary.map(([name,value,unit])=><div key={name}><dt>{name}</dt><dd>{money(value,2)} {unit}</dd></div>)}</dl><small>Model output is a transparent scenario—not consensus or a recommendation to transact.</small></div></div>
    <h2 className="section-title">Expectations framework</h2><Expectations rows={model.expectations.map(x=>[x[0],x[1],x[2],x[3]])}/>
    <h2 className="section-title">Valuation scenarios</h2><div className="sector-scenarios">{deep.scenarios.map(([name,narrative,low,high])=><article className={name.toLowerCase()} key={name}><span>{name.toUpperCase()}</span><b>{low}× – {high}×</b><p>{narrative}</p></article>)}</div><p className="section-note">{deep.valuation}</p>
    <AtlasBridge links={model.links}/><CommercialResearch deep={deep}/><h2 className="section-title">Catalyst and decision calendar</h2><Catalysts items={profile.catalysts.map((x,i)=>[i===0?"Near term":"Monitor",x,"Evidence must transmit into the selected model inputs",i===0?"Update forecast":"Hold conclusion until confirmed"])}/><ThesisRules rules={model.breaks}/>
    <div className="finance-columns"><section><h2 className="section-title">Catalysts</h2><div className="factor-grid">{profile.catalysts.map(x=><article className="catalyst" key={x}><span>CATALYST</span><h3>{x}</h3></article>)}</div></section><section><h2 className="section-title">Risks</h2><div className="factor-grid">{profile.risks.map(x=><article className="risk" key={x}><span>RISK</span><h3>{x}</h3></article>)}</div></section></div>
    <ResearchFooter source={deep.source} formula={deep.valuation}/>
  </section>
}

function EquinixRevision(){return <div className="pm-company revision-append"><RevisionMonitor title="Equinix raised the 2026 earnings floor" subtitle="Q1 operating strength lifted revenue, EBITDA and AFFO guidance; the higher capex plan makes conversion into stabilized returns the next debate." items={[
  {date:"2026-02-11",kind:"Initial FY guide",metric:"AFFO / share",prior:"2025 actual: $38.33",current:"$41.93–42.74",direction:"up",readthrough:"Initial guidance implied 9–12% reported growth."},
  {date:"2026-04-29",kind:"Revised FY guide",metric:"AFFO / share",prior:"$41.93–42.74",current:"$42.31–43.11",direction:"up",readthrough:"The midpoint rose $0.38 after Q1 operating outperformance."},
  {date:"2026-04-29",kind:"Revised FY guide",metric:"Revenue",prior:"$10.123–10.223bn",current:"$10.144–10.244bn",direction:"up",readthrough:"A $21m operating raise; the foreign-exchange contribution was minimal."},
  {date:"2026-04-29",kind:"Capital plan",metric:"Total capex",prior:"$3.66–4.16bn implied",current:"~$4.10bn",direction:"flat",readthrough:"Spend is near the upper end of the initial envelope; returns matter more than headline growth."}
]} scorecard={[
  {period:"Q1 2026",metric:"AFFO / share",expected:"FY guide run-rate",reported:"$10.79",result:"Above midpoint pace",tone:"positive"},
  {period:"Q1 2026",metric:"Adj. EBITDA margin",expected:"51–52% Q1 guide",reported:"51%",result:"Within range",tone:"positive"},
  {period:"Q1 2026",metric:"Revenue",expected:"$2.496–2.536bn guide",reported:"$2.444bn",result:"Timing-adjusted above midpoint",tone:"neutral"},
  {period:"FY 2026",metric:"AFFO / share",expected:"Revised company guide",reported:"$42.31–43.11",result:"Pending",tone:"neutral"}
]} sources={[["Equinix initial 2026 outlook","https://investor.equinix.com/news-events/press-releases/detail/1096/equinix-provides-robust-2026-outlook-driven-by-strong"],["Equinix Q1 2026 revision","https://investor.equinix.com/news-events/press-releases/detail/1107/equinix-reports-first-quarter-results-and-raises-full-year"]]}/></div>}

export function DecisionCard({side,price,target,bear,horizon,catalyst,breakRule,status,confidence,currency="$"}){
  const expected=price&&target!=null?100*(target/price-1):null,downside=price&&bear!=null?100*(bear/price-1):null;
  return <section className="pm-decision"><div><span>RECOMMENDATION</span><b>{side}</b><small>{confidence} conviction · {horizon}</small></div><div><span>MARKET PRICE</span><b>{price?`${currency}${money(price,2)}`:"Feed unavailable"}</b><small>Live when market service responds</small></div><div><span>BASE VALUE</span><b>{target==null?"Model below":`${currency}${money(target,2)}`}</b><small>{expected==null?"Per-share bridge pending":pct(expected)}</small></div><div><span>BEAR VALUE</span><b>{bear==null?"Model below":`${currency}${money(bear,2)}`}</b><small className="negative">{downside==null?"Entity bridge pending":pct(downside)}</small></div><div><span>RESEARCH STATUS</span><b>{status}</b><small>Conclusion, not a portfolio position</small></div><article><span>PRIMARY CATALYST</span><b>{catalyst}</b><small>THESIS BREAK · {breakRule}</small></article></section>
}

function AtlasBridge({links}){const tabFor=name=>/macro|china|policy/i.test(name)?"countries":/iron|steel|battery|nickel|copper|energy|power/i.test(name)?"commodities":/shipping|shipbuilding|trade|data center|ev/i.test(name)?"chain":"research";return <><h2 className="section-title">Atlas evidence bridge</h2><p className="section-note">Open the upstream evidence behind each financial assumption. The linked page provides the physical or macro signal; the company model determines earnings sensitivity.</p><div className="atlas-bridge">{links.map(([name,detail],i)=><button type="button" key={name} onClick={()=>navigateAtlas(tabFor(name),name)}><span>{String(i+1).padStart(2,"0")} · {name}</span><b>{detail}</b><small>Open linked {tabFor(name)} analysis →</small></button>)}</div></>}

function Range({label,value,set,min,max,step,unit,reported}){return <label className="pm-range"><span>{label}</span><b>{money(value,step<1?2:1)}{unit}</b><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>set(Number(e.target.value))}/><small>{reported}</small></label>}

function Expectations({rows}){return <div className="pm-expectations"><div><span>Metric</span><span>Company / public anchor</span><span>Atlas estimate</span><span>Difference</span></div>{rows.map(r=><article key={r[0]}><b>{r[0]}</b><span>{r[1]}</span><strong>{r[2]}</strong><em>{r[3]}</em></article>)}</div>}

function RevisionMonitor({title,subtitle,items,scorecard,sources}){
  return <section className="revision-monitor"><header><div><span>EXPECTATIONS MONITOR</span><h2>{title}</h2><p>{subtitle}</p></div><aside><b>{items.filter(x=>x.direction==="up").length} upward</b><small>{items.filter(x=>x.direction==="flat").length} maintained</small></aside></header><div className="revision-grid">{items.map((x,i)=><article className={x.direction} key={`${x.date}-${x.metric}-${i}`}><span>{x.date} · {x.kind}</span><h3>{x.metric}</h3><div><small>PRIOR</small><b>{x.prior}</b><i>→</i><small>CURRENT / ACTUAL</small><strong>{x.current}</strong></div><p>{x.readthrough}</p></article>)}</div><h3 className="revision-subtitle">Reported versus public expectation</h3><div className="earnings-scorecard"><div><span>Period</span><span>Metric</span><span>Expectation</span><span>Reported</span><span>Read-through</span></div>{scorecard.map(x=><article key={`${x.period}-${x.metric}`}><b>{x.period}</b><span>{x.metric}</span><span>{x.expected}</span><strong>{x.reported}</strong><em className={x.tone}>{x.result}</em></article>)}</div><footer><p><b>Boundary:</b> this tracks company guidance and explicitly disclosed operating expectations—not institutional consensus. It is still decision-useful because revisions reveal the direction and magnitude of management’s information update.</p>{sources.map(([label,url])=><a key={url} href={url} target="_blank" rel="noreferrer">{label} ↗</a>)}</footer></section>
}

export function Catalysts({items}){return <div className="pm-catalysts">{items.map(([date,event,expected,action])=><article key={event}><span>{date}</span><b>{event}</b><p>{expected}</p><small>PM ACTION · {action}</small></article>)}</div>}

function ResearchFooter({source,formula}){return <details className="valuation-method" open><summary>Method, compliance and audit trail</summary><div><article><b>Model</b><code>{formula}</code><p>All editable inputs are analyst assumptions. Reported results and company guidance remain separately labelled.</p></article><article><b>Compliance</b><p>Public sources only. No material nonpublic information, fabricated consensus or undisclosed proprietary data.</p></article><article><b>Forecast discipline</b><p>Outputs are research scenarios, not recommendations to transact. Forecast revisions must be timestamped rather than overwritten.</p></article></div><a href={source} target="_blank" rel="noreferrer">Open primary company source ↗</a></details>}

function CliffsWorkbench({company,profile,deep,quote,onBack}){
  const [shipments,setShipments]=useState(16.75),[revenueTon,setRevenueTon]=useState(1160),[ebitdaTon,setEbitdaTon]=useState(95),[capex,setCapex]=useState(.7),[cashBelow,setCashBelow]=useState(.62),[multiple,setMultiple]=useState(6),[netDebt,setNetDebt]=useState(7.0);
  const shares=.50,ebitda=shipments*ebitdaTon/1000,revenue=shipments*revenueTon/1000,fcf=ebitda-capex-cashBelow,target=Math.max(0,(ebitda*multiple-netDebt)/shares),bear=Math.max(1,((shipments*45/1000)*4.5-netDebt)/shares),price=quote?.live?quote.price:null;
  const signal=Math.round(50+(revenueTon-1050)/8+(shipments-16)*8+(ebitdaTon-70)/3);
  const narrative=companyNarratives["cleveland-cliffs"];
  const keyData=[["Ticker","NYSE: CLF"],["Sector","Steel"],["Share price",price?`$${money(price,2)}`:"Feed unavailable"],["Atlas stance",deep.stance],["Conviction","Medium-low"],["Base value",`$${money(target,2)}`],["Bear value",`$${money(bear,2)}`],["Net debt",`$${money(netDebt,1)}bn`],["As of",deep.asOf]];
  return <section className="directory-page pm-company"><button className="finance-back" onClick={onBack}>← Companies by industry</button>
    <ResearchNote eyebrow="STEEL · FUNDAMENTAL LONG/SHORT WORKBENCH" companyName="Cleveland-Cliffs" strapline={narrative?.strapline} narrative={narrative} keyData={keyData} quote={quote} symbol="CLF" disclosure={DISCLOSURE}/>
    <DecisionCard side={deep.stance} price={price} target={target} bear={bear} horizon="6–12 months" confidence="Medium-low" status={target>price?"UPSIDE · CONFIRMATION NEEDED":"VALUATION NOT SUPPORTIVE"} catalyst="Quarterly EBITDA/t and free-cash-flow confirmation" breakRule="Two quarters of negative FCF after price recovery"/>
    <InstitutionalBrief debate={profile.debate} variant={deep.variant} estimate="Recovery estimates should move with EBITDA/ton and free cash flow—not HRC price alone." catalyst="Contract resets, shipment recovery and positive quarterly free cash flow" risk="Auto weakness, high fixed-cost absorption and leverage preventing equity value creation"/>
    <InvestmentTransmission caseData={investmentCases.clf}/>
    <div className="pm-three-sentence"><span>ATLAS DEMAND SIGNAL</span><p>{signal}/100 — {signal>=65?"strengthening":"mixed, confirmation required"}. 2025 was a trough year: US$18.6bn revenue produced only US$37m of adjusted EBITDA. The variant case is that better trade conditions, an expired loss-making slab contract and cost action produce more earnings recovery than a simple HRC-beta view captures.</p></div>
    <h2 className="section-title">Driver-based 2026 model</h2><div className="pm-model"><div className="pm-inputs"><Range label="Steel shipments" value={shipments} set={setShipments} min={14} max={19} step={.25} unit="m tons" reported="Company 2026 outlook: 16.5–17.0m net tons"/><Range label="Realized revenue / ton" value={revenueTon} set={setRevenueTon} min={950} max={1400} step={10} unit="$/t" reported="Analyst assumption; combines product and customer mix"/><Range label="EBITDA / ton" value={ebitdaTon} set={setEbitdaTon} min={20} max={180} step={5} unit="$/t" reported="Key operating-leverage assumption"/><Range label="Capital expenditure" value={capex} set={setCapex} min={.5} max={1.1} step={.05} unit="bn" reported="Company 2026 expectation: approximately US$700m"/><Range label="Cash interest, tax + WC" value={cashBelow} set={setCashBelow} min={.3} max={1.1} step={.05} unit="bn" reported="Simplified cash bridge; requires quarterly refinement"/><Range label="Target EV / EBITDA" value={multiple} set={setMultiple} min={3} max={9} step={.25} unit="×" reported="Cycle-sensitive analyst assumption"/><Range label="Net debt" value={netDebt} set={setNetDebt} min={5} max={10} step={.25} unit="bn" reported="Editable until latest definition is reconciled"/></div><div className="pm-output"><span>ATLAS 2026 OUTPUT</span><b>${money(target,2)} / share</b><dl><div><dt>Revenue</dt><dd>${money(revenue,2)}bn</dd></div><div><dt>Adjusted EBITDA</dt><dd>${money(ebitda,2)}bn</dd></div><div><dt>Free cash flow proxy</dt><dd className={fcf>=0?"positive":"negative"}>${money(fcf,2)}bn</dd></div><div><dt>Implied equity value</dt><dd>${money(Math.max(0,ebitda*multiple-netDebt),2)}bn</dd></div></dl><small>500m diluted-share placeholder · replace with latest weighted and fully diluted bridge.</small></div></div>
    <h2 className="section-title">What is priced in?</h2><p className="section-note">At the selected multiple and net debt, the live price implies approximately <b>{price?money((price*shares+netDebt)/multiple,2):"—"}bn</b> of EBITDA, or <b>{price?money(((price*shares+netDebt)/multiple)*1000/shipments,0):"—"}$/t</b>. Compare that hurdle with the editable Atlas forecast.</p>
    <Expectations rows={[["2026 shipments","16.5–17.0m company outlook",`${money(shipments,2)}m`,`${money(shipments-16.75,2)}m vs midpoint`],["Adjusted EBITDA","No fabricated consensus",`$${money(ebitda,2)}bn`,"Atlas scenario"],["Free cash flow","No public anchor stored",`$${money(fcf,2)}bn`,fcf>=0?"Positive":"Negative"],["Valuation","Live price-implied hurdle",`$${money(target,2)}/share`,price?pct(100*(target/price-1)):"price pending"]]}/>
    <RevisionMonitor title="CLF earnings recovery is now observable" subtitle="The annual volume and capex framework is unchanged, but quarterly EBITDA, pricing and cash conversion have improved materially." items={[
      {date:"2026-04-20",kind:"Q1 actual",metric:"Adjusted EBITDA",prior:"Q4 2025: -$21m",current:"Q1 2026: $95m",direction:"up",readthrough:"The turn began despite an $80m cold-weather energy impact."},
      {date:"2026-07-23",kind:"Q2 actual",metric:"Adjusted EBITDA",prior:"Q1 2026: $95m",current:"Q2 2026: $286m",direction:"up",readthrough:"Sequential EBITDA nearly tripled and free cash flow turned positive."},
      {date:"2026-07-23",kind:"Q3 guide",metric:"Adjusted EBITDA",prior:"Q2 2026: $286m",current:"Q3 guide: ~$575m",direction:"up",readthrough:"The guide implies another doubling; this is now the key hurdle for the turnaround."},
      {date:"2026-07-23",kind:"FY guide",metric:"Shipments / capex",prior:"16.5–17.0m / ~$700m",current:"Maintained",direction:"flat",readthrough:"Momentum is being driven by price, cost and mix—not a higher annual volume guide."}
    ]} scorecard={[
      {period:"Q1 2026",metric:"Steel shipments",expected:"FY run-rate: 4.13–4.25m/qtr",reported:"4.108m",result:"Near low end",tone:"neutral"},
      {period:"Q2 2026",metric:"Adjusted EBITDA",expected:"Sequential improvement",reported:"$286m",result:"Confirmed",tone:"positive"},
      {period:"Q2 2026",metric:"Free cash flow",expected:"Positive",reported:"Positive",result:"Met",tone:"positive"},
      {period:"Q3 2026",metric:"Adjusted EBITDA",expected:"Company guide",reported:"~$575m guide",result:"Pending",tone:"neutral"}
    ]} sources={[["CLF Q1 2026 results","https://www.clevelandcliffs.com/investors/sec-filings/all-sec-filings/content/0000764065-26-000067/0000764065-26-000067.pdf"],["CLF Q2 2026 results","https://www.clevelandcliffs.com/investors/news-events/press-releases/detail/700/cleveland-cliffs-reports-second-quarter-2026-results"]]}/>
    <AtlasBridge links={deep.atlasLinks}/><CommercialResearch deep={deep}/><CliffsNucorPair clf={{price,target,ebitdaTon,shipments}}/>
    <h2 className="section-title">Catalyst and decision calendar</h2><Catalysts items={[["Quarterly","CLF earnings","EBITDA/t and cash conversion improve","Add only if FCF confirms"],["Monthly","US HRC + steel imports","Realized-price backdrop strengthens","Revise revenue/t, not target multiple"],["Monthly","US auto production","Contract tons and utilization hold","Cut shipments if production weakens"],["Annual resets","Automotive contracts","Pricing captures cost and tariff backdrop","Rebuild mix and margin"]]}/>
    <ThesisRules rules={[["Shipments","Below 16.0m run-rate","Reduce"],["EBITDA/t","Below $60 with HRC recovery","Exit thesis"],["Free cash flow","Negative for two confirming quarters","Exit"],["Net debt","Rises despite positive EBITDA","No add"]]}/>
    <ResearchFooter source={deep.source} formula="Revenue = shipments × revenue/t; EBITDA = shipments × EBITDA/t; FCF proxy = EBITDA − capex − cash below EBITDA; equity value = EBITDA × EV/EBITDA − net debt"/>
  </section>
}

function CliffsNucorPair({clf}){
  const [nueShip,setNueShip]=useState(28),[nueMargin,setNueMargin]=useState(270),[nueMultiple,setNueMultiple]=useState(7),nueDebt=4,nueShares=.23;
  const nueEbitda=nueShip*nueMargin/1000,nueTarget=(nueEbitda*nueMultiple-nueDebt)/nueShares;
  return <section className="pair-workbench"><header><div><span>RELATIVE VALUE · CLF VS NUE</span><h2>Integrated BF turnaround versus EAF quality compounder</h2></div><b>Research pair · direction remains model-dependent</b></header><div className="pair-columns"><article><span>CLF</span><b>${money(clf.target,2)}</b><p>{money(clf.shipments,2)}m tons · ${money(clf.ebitdaTon,0)}/t EBITDA</p><small>Auto-heavy · ore integrated · higher leverage</small></article><article><span>NUE</span><b>${money(nueTarget,2)}</b><Range label="NUE shipments" value={nueShip} set={setNueShip} min={24} max={32} step={.5} unit="m tons" reported="2025 external customer tons: 26.6m"/><Range label="NUE EBITDA / ton" value={nueMargin} set={setNueMargin} min={150} max={400} step={10} unit="$/t" reported="Analyst normalized margin assumption"/><Range label="NUE EV / EBITDA" value={nueMultiple} set={setNueMultiple} min={4} max={10} step={.25} unit="×" reported="Quality/cycle assumption"/></article></div><div className="pair-scenarios"><span>Scenario</span><span>CLF read-through</span><span>NUE read-through</span><span>Pair judgment</span>{[["HRC +$100/t","Higher operating leverage","Positive steel-mill spread","CLF can outperform if cash converts"],["Scrap +$50/t","Limited direct exposure","Metal margin pressure","Relative CLF benefit"],["Auto recession","High volume/mix risk","More diversified","Favor NUE"],["Data-center build","Moderate flat-steel pull","Construction/products exposure","Favor NUE"]].flatMap((r,i)=>r.map((x,j)=><b key={`${i}-${j}`}>{x}</b>))}</div><a href="https://investors.nucor.com/news/news-details/2026/Nucor-Reports-Results-for-the-Second-Quarter-of-2026/default.aspx" target="_blank" rel="noreferrer">Nucor Q2 2026 primary source ↗</a></section>
}

function EquinixWorkbench({deep,quote,onBack}){
  const [affo,setAffo]=useState(42.71),[multiple,setMultiple]=useState(26),[bookings,setBookings]=useState(12),[capex,setCapex]=useState(4.1),[margin,setMargin]=useState(51);
  const price=quote?.live?quote.price:null,qualityAdj=1+(bookings-10)*.008+(margin-51)*.01-(capex-4.1)*.025,atlasAffo=affo*qualityAdj,target=atlasAffo*multiple,bear=atlasAffo*.9*20,impliedAffo=price?price/multiple:null,signal=Math.round(55+bookings*1.4+(margin-49)*3-(capex-4)*4);
  const narrative=companyNarratives.equinix;
  const keyData=[["Ticker","NASDAQ: EQIX"],["Sector","Data centers"],["Share price",price?`$${money(price,2)}`:"Feed unavailable"],["Atlas stance",deep.stance],["Conviction","Medium"],["Base value",`$${money(target,2)}`],["Bear value",`$${money(bear,2)}`],["As of",deep.asOf]];
  return <section className="directory-page pm-company"><button className="finance-back" onClick={onBack}>← Companies by industry</button>
    <ResearchNote eyebrow="DATA CENTERS · FUNDAMENTAL WORKBENCH" companyName="Equinix" strapline={narrative?.strapline} narrative={narrative} keyData={keyData} quote={quote} symbol="EQIX" disclosure={DISCLOSURE}/>
    <DecisionCard side={deep.stance} price={price} target={target} bear={bear} horizon="9–15 months" confidence="Medium" status={target>price?"UPSIDE · CONFIRMATION NEEDED":"VALUATION FULL"} catalyst="Bookings conversion and AFFO/share revisions" breakRule="AFFO guidance cut or capex rises without stabilized capacity"/>
    <InstitutionalBrief debate={profile.debate} variant={deep.variant} estimate="Q1 raised the AFFO floor; the next revision depends on bookings conversion and development returns." catalyst="AFFO/share revisions and powered-capacity stabilization" risk="Capex growth without incremental AFFO, power delays or rate-driven multiple compression"/>
    <InvestmentTransmission caseData={investmentCases.equinix}/>
    <div className="pm-three-sentence"><span>POWERED-CAPACITY PRESSURE SIGNAL</span><p>{signal}/100. Equinix entered 2026 with record bookings, recurring-revenue momentum and raised AFFO guidance after Q1. The variant view is that scarce power and dense interconnection ecosystems support better pricing and utilization than conventional data-center supply models imply.</p></div>
    <h2 className="section-title">Forward AFFO model</h2><div className="pm-model"><div className="pm-inputs"><Range label="2026 AFFO / share anchor" value={affo} set={setAffo} min={38} max={48} step={.1} unit="$" reported="Company revised guidance: $42.31–$43.11"/><Range label="Bookings / demand growth" value={bookings} set={setBookings} min={0} max={25} step={1} unit="%" reported="Atlas assumption used as conversion adjustment"/><Range label="Adjusted EBITDA margin" value={margin} set={setMargin} min={47} max={55} step={.25} unit="%" reported="Company 2026 guidance approximately 51%"/><Range label="Total capital expenditure" value={capex} set={setCapex} min={3} max={5.5} step={.1} unit="bn" reported="Company Q1 outlook approximately $4.1bn"/><Range label="Target P / AFFO" value={multiple} set={setMultiple} min={16} max={34} step={.5} unit="×" reported="Rate- and growth-sensitive analyst assumption"/></div><div className="pm-output"><span>ATLAS FORWARD OUTPUT</span><b>${money(target,2)} / share</b><dl><div><dt>Adjusted AFFO/share</dt><dd>${money(atlasAffo,2)}</dd></div><div><dt>Selected multiple</dt><dd>{money(multiple,1)}×</dd></div><div><dt>Market-implied AFFO</dt><dd>{impliedAffo?`$${money(impliedAffo,2)}`:"—"}</dd></div><div><dt>Demand signal</dt><dd>{signal}/100</dd></div></dl><small>The demand adjustment is an Atlas prototype—not company guidance or consensus.</small></div></div>
    <Expectations rows={[["2026 revenue","$10.144–10.244bn guidance","Guidance midpoint retained","No consensus invented"],["2026 AFFO/share","$42.31–43.11 guidance",`$${money(atlasAffo,2)}`,`$${money(atlasAffo-42.71,2)} vs midpoint`],["EBITDA margin","~51% guidance",`${money(margin,1)}%`,`${money(margin-51,1)} pp`],["Total capex","~$4.1bn guidance",`$${money(capex,1)}bn`,`${money(capex-4.1,1)}bn`]]}/>
    <AtlasBridge links={deep.atlasLinks}/><h2 className="section-title">Catalyst and decision calendar</h2><Catalysts items={[["Quarterly","Bookings and MRR","Demand converts into recurring revenue","Raise AFFO only after conversion"],["Quarterly","Development pipeline","Powered capacity stabilizes on time","Compare capex with incremental AFFO"],["Policy / utility","Grid interconnection decisions","Capacity timing improves or slips","Update regional supply score"],["Fed / credit","Rates and spreads","Cost of capital changes","Update multiple, not operations"]]}/><ThesisRules rules={[["AFFO/share","Guidance reduced below $42","Reduce"],["Bookings","Growth below 5% with slowing MRR","Review thesis"],["Development","Capex rises >10% without capacity benefit","No add"],["Valuation","Expected return below 10%","Do not initiate"]]}/><ResearchFooter source={deep.source} formula="Atlas AFFO/share = company guidance midpoint × demand/margin/capex adjustment; value/share = adjusted AFFO/share × P/AFFO"/>
  </section>
}

function ThesisRules({rules}){return <><h2 className="section-title">Quantified thesis-break rules</h2><div className="thesis-rules">{rules.map(([metric,trigger,action])=><article key={metric}><span>{metric}</span><b>{trigger}</b><small>{action}</small></article>)}</div></>}
